FROM mysql:5.6

ENV MYSQL_ROOT_PASSWORD="pass"
ENV MYSQL_DATABASE="mysql"

COPY seed-data.sql /docker-entrypoint-initdb.d/db.sql
COPY my.cnf /etc/mysql/my.cnf
RUN /entrypoint.sh mysqld & sleep 30 && killall mysqld
RUN rm /docker-entrypoint-initdb.d/db.sql